export let GET_PARTY_PENDING = "GET_PARTY_PENDING";
export let GET_PARTY_SUCCESS = "GET_PARTY_SUCCESS";
export let GET_PARTY_ERROR = "GET_PARTY_ERROR";

export let POST_PARTY_PENDING = "POST_PARTY_PENDING";
export let POST_PARTY_SUCCESS = "POST_PARTY_SUCCESS";
export let POST_PARTY_ERROR = "POST_PARTY_ERROR";

export let DELETE_PARTY_PENDING = "DELETE_PARTY_PENDING";
export let DELETE_PARTY_SUCCESS = "DELETE_PARTY_SUCCESS";
export let DELETE_PARTY_ERROR = "DELETE_PARTY_ERROR";

export let GET_VOTER_PENDING = "GET_VOTER_PENDING";
export let GET_VOTER_SUCCESS = "GET_VOTER_SUCCESS";
export let GET_VOTER_ERROR = "GET_VOTER_ERROR";

export let POST_VOTER_PENDING = "POST_VOTER_PENDING";
export let POST_VOTER_SUCCESS = "POST_VOTER_SUCCESS";
export let POST_VOTER_ERROR = "POST_VOTER_ERROR";

export let DELETE_VOTER_PENDING = "DELETE_VOTER_PENDING";
export let DELETE_VOTER_SUCCESS = "DELETE_VOTER_SUCCESS";
export let DELETE_VOTER_ERROR = "DELETE_VOTER_ERROR";

export let GET_ELECTION_PENDING = "GET_ELECTION_PENDING";
export let GET_ELECTION_SUCCESS = "GET_ELECTION_SUCCESS";
export let GET_ELECTION_ERROR = "GET_ELECTION_ERROR";

export let POST_ELECTION_PENDING = "POST_ELECTION_PENDING";
export let POST_ELECTION_SUCCESS = "POST_ELECTION_SUCCESS";
export let POST_ELECTION_ERROR = "POST_ELECTION_ERROR";

export let DELETE_ELECTION_PENDING = "DELETE_ELECTION_PENDING";
export let DELETE_ELECTION_SUCCESS = "DELETE_ELECTION_SUCCESS";
export let DELETE_ELECTION_ERROR = "DELETE_ELECTION_ERROR";