export let GET_VOTE_PENDING="GET_VOTE_PENDING";
export let GET_VOTE_SUCCESS="GET_VOTE_SUCCESS";
export let GET_VOTE_ERROR="GET_VOTE_ERROR";

export let POST_VOTE_PENDING ="POST_VOTE_PENDING";
export let POST_VOTE_SUCCESS ="POST_VOTE_SUCCESS";
export let POST_VOTE_ERROR ="POST_VOTE_ERROR";

export let DELETE_VOTE_PENDING ="DELETE_VOTE_PENDING";
export let DELETE_VOTE_SUCCESS ="DELETE_VOTE_SUCCESS";
export let DELETE_VOTE_ERROR ="DELETE_VOTE_ERROR";
